version: '3.6'

services:  
  backend-pruebas:
    image: challenge
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
        - 8082:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Development

    networks: 
     - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge